### ISSUE TITLE
Cut finder design decisions and to-do items.

### ISSUE THREAD

**Issue by Ibrahim-Shehzad** [Qiskit-Extensions/circuit-knitting-toolbox#491]
- [x] Finish adding tests for cut_finding.py to get to 100% coverage.
- [x] Deprecate old tutorial.
- [x] Remove any remaining linting errors.
- [x] Correct/improve the function and class names.
- [x] Decide on public vs private methods and finalize doc strings.
- [x] Develop new classes for specifying optimization settings.
- [x] Item 4 feeds into overall design changes, to comply with principles like DRY.

**Comment by garrison** [comment]
Completed by #520.
